### ISSUE TITLE
Matrix multiplication vs elementwise multiplication

### ISSUE THREAD

**Issue by ashnair1** [mortcanty/CRC4Docker#25]
Hi @mortcanty, 

In numpy, the `*` operator in numpy corresponds to element-wise multiplication whereas `np.matmul` or (`@` operator since Python 3.5) corresponds to matrix multiplication. So should'nt the notation be fixed in places such as [this](https://github.com/mortcanty/CRC4Docker/blob/e52a6e88d4469284a071c0b96d009f6684dbb2ea/src/scripts/iMad.py#L169)?

**Comment by mortcanty** [comment]
That's right, it is confusing. But S = cpm.covariance() returns a matrix object S and not a numpy array so s11*s22 etc is interpreted as matrix multiplication.

**Comment by ashnair1** [comment]
Ah I see. That makes sense. Thanks for clearing it up.

**Comment by ashnair1** [comment]
As a side note, what is your preferred method of contact if a reader of your book has some questions (not necessarily code related)? 

GIthub issues are usually used for code related problems so I'm hesitant to use it for general conceptual questions. Alternatively, Github has a new feature called Discussions that could be useful if you are interested in enabling it in your repo.

**Comment by mortcanty** [comment]
email probably best for me. I'll look into discussions, thanks
