### ISSUE TITLE
Ensure sum of positive correlations between X and U is positive

### ISSUE THREAD

**Issue by ashnair1** [mortcanty/CRC4Docker#27]
Hi @mortcanty,

I had two questions regarding [this section](https://github.com/mortcanty/CRC4Docker/blob/e52a6e88d4469284a071c0b96d009f6684dbb2ea/src/scripts/iMad.py#L202).

1. The comment states that the aim of this section is to ensure sum of positive correlations between X and U is positive. What exactly is the purpose of this step and what is X in this case? From the book it is understood that U is the new multispectral image generated from the eigenvalue problem but it's unclear what X is.
2. This step appears to be missing in the `iMad_tf.py` script. Is there a reason for this or did I miss something?

Thanks

**Comment by mortcanty** [comment]
Thanks for your interest, it is appreciated.

1. There are ambiguities in the relative signs of the canonical transformations, but it is only essential to ensure that the canonical variates are positively correlated. When this is done, there is still an ambiguity in the relative signs which affects the overall signs of the MAD variates, but not their absolute values. The additional step is intended to remove that ambiguity, but it's not essential. X is the first image.
2. I didn't bother to include the step in the tensorflow implementation (laziness, also the script isn't mentioned in my book).

**Comment by ashnair1** [comment]
Ah I see. So this is why the outputs of the `iMad.py` and `iMad_tf.py` differ in their signs i.e. if you compare bands of `iMad.py` output and `iMad_tf.py` output their signs are sometimes different. 

Where do these sign ambiguities come from though?

Edit: Oh wait, this is because of the eigenvectors isn't it? Even after normalisation your eigenvectors will still be `±x`

**Comment by mortcanty** [comment]
Yep. If you're really interested, you might have a look at 
https://old-www.sandia.gov/~tgkolda/pubs/pubfiles/SAND2007-6422.pdf
I haven't read it myself, I admit. :)

**Comment by ashnair1** [comment]
Thanks a lot for the clarification and the reference.
