### ISSUE TITLE
About linear stretching

### ISSUE THREAD

**Issue by ashnair1** [mortcanty/CRC4Docker#30]
Hi @mortcanty,

Is this [lin2pcstr function](https://github.com/mortcanty/CRC4Docker/blob/e52a6e88d4469284a071c0b96d009f6684dbb2ea/src/auxil/auxil1.py#L481) doing the 2% linear stretch **and** histogram equalisation? 

I ask because a standard linear stretch could be done as follows:

```
import numpy as np

def stretch(x, lower, upper, maxout=255, minout=0):
    a = (maxout - minout) / (upper - lower)
    b = minout - a * lower
    scaled = (a * x + b)
    scaled = np.clip(scaled, minout, maxout)
    return scaled

# Standard Linear stretch
lower = img.min()
upper = img.max()
scaled = stretch(img, lower, upper)

# 2% Linear stretch
lower = np.nanpercentile(img,2)
upper = np.nanpercentile(img, 98)
scaled2 = stretch(img, lower, upper)
                
```

Just wanted to be sure if I'm understanding the steps correctly. 

**Edit**: I notice you already have [bytestr()](https://github.com/mortcanty/CRC4Docker/blob/e52a6e88d4469284a071c0b96d009f6684dbb2ea/src/auxil/auxil1.py#L501) for stretching to the full byte range (0 to 255). So shouldn't the 2% stretch simply be `bytestr(x, rng=[np.nanpercentile(img,2), np.nanpercentile(img,98)])`?

**Comment by mortcanty** [comment]
No, just linear 2pc stretch. (Histogram equalization is the function histeqstr().) It is unnecessarily complicated. Your code is much better.

**Comment by ashnair1** [comment]
Thanks for the clarification. One follow up question, when I plotted the stretched histograms on the chagemap produced by `iMad.py` the results were slightly different. Is this significant?

Orange is mine, blue is yours.

![image](https://user-images.githubusercontent.com/32295036/121555842-665df880-ca24-11eb-812b-14363f15c896.png)

**Comment by mortcanty** [comment]
As far as it is just for visualization, I don't think so.
